//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.04 at 11:58:43 PM MESZ 
//


package org.jvnet.hyperjaxb3.ejb.tests.issues;

import org.jvnet.jaxb2_commons.xml.bind.ContextPathAware;

public class RoundtripTest
    extends org.jvnet.hyperjaxb3.ejb.test.RoundtripTest
    implements ContextPathAware
{


    public String getContextPath() {
        return "org.jvnet.hyperjaxb3.ejb.tests.issuesignored:org.jvnet.hyperjaxb3.ejb.tests.issues:net.opengis.gml.v_3_1_1:org.w3.smil.v_2_0:org.w3.smil.v_2_0.language";
    }

    public String getPersistenceUnitName() {
        return "org.jvnet.hyperjaxb3.ejb.tests.issues";
    }

}
