
package org.jvnet.hyperjaxb3.samples.pows.bindings;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 09:55 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderService", targetNamespace = "urn:org:javanet:hyperjaxb3:samples:po-ws:po-service.wsdl", wsdlLocation = "file:/C:/Projects/hyperjaxb3/hyperjaxb3/samples/po-ws/src/wsdl/po-service.wsdl")
public class OrderService
    extends Service
{

    private final static URL ORDERSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Projects/hyperjaxb3/hyperjaxb3/samples/po-ws/src/wsdl/po-service.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ORDERSERVICE_WSDL_LOCATION = url;
    }

    public OrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderService() {
        super(ORDERSERVICE_WSDL_LOCATION, new QName("urn:org:javanet:hyperjaxb3:samples:po-ws:po-service.wsdl", "OrderService"));
    }

    /**
     * 
     * @return
     *     returns OrderServicePortType
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderServicePortType getOrderServicePort() {
        return (OrderServicePortType)super.getPort(new QName("urn:org:javanet:hyperjaxb3:samples:po-ws:po-service.wsdl", "OrderServicePort"), OrderServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderServicePortType
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderServicePortType getOrderServicePort(WebServiceFeature... features) {
        return (OrderServicePortType)super.getPort(new QName("urn:org:javanet:hyperjaxb3:samples:po-ws:po-service.wsdl", "OrderServicePort"), OrderServicePortType.class, features);
    }

}
